### ISSUE TITLE
CK3 1.1 compatibility

### ISSUE THREAD

**Issue by cherisong** [cherisong/Carnalitas#101]
merge changes to
- [ ] character window friends list, concubines
- [ ] court window prisoner buttons (?)
- [ ] 00_core_tenets (not actually in carnalitas, just reminding myself for carnM)
- check for undocumented changes in any other overwrites

**Comment by Triskelia** [comment]
To make things easier for future updates. I'd suggest that we upload the vanilla files we overwrite as .info (or any other text file format other than .txt. We could also put them in a folder that will not be shipped with our releases)
That way, when a CK3 update is released, we just have to copy it into the .info, and Git will highlight the vanilla changes, that we can then easily copy into our modified files. 
It would also allow us to easily compare our modified files to the vanilla files right from Git, whenever we need it, so we can easily keep track of what is from us, and what is from Pdx.

I'm suggesting this since it's common practice when overwriting files with git

**Comment by cherisong** [comment]
done and dusted
