### ISSUE TITLE
Problems with genetic trait inheritance

### ISSUE THREAD

**Issue by Luis276** [cherisong/Carnalitas#18]
**Describe the bug**
Having problems trying to inherit dick and tits sizes.
Neither is inherited with the same frequency as other congenital traits.

**To Reproduce**
1. Get a wife with tits_big_3 and a husband with dick_big_3.
2. Have kids.
3. Wait for them to become adults.

**Expected behavior**
Kids are supposed to have big dicks and tits when they become adults.

**Game Version**
Ck3 1.0.3

**Mods (List your mods, preferably with the load order they have in your launcher, as well as their version)**
1. Visible Health, Fertility and Stress
2. Carnalitas
3. Nude Inspect
4. DW Toska
5. Free Console Access

**Comment by cherisong** [comment]
This is likely to be intended behavior.

Although the wife may have tits_big_3, the husband may not have the gene. The same goes for the husband and dick_big_3.

The expected behavior is that the children have the appropriate congenital trait roughly 25% of the time (see [CK3 wiki article on breeding traits](https://ck3.paradoxwikis.com/Breeding)). They are also much more likely to have children with the appropriate congenital trait.

Try playing for a few more generations and see if it fixes your issue.

**Comment by Luis276** [comment]
I honestly didn't know about the active and inactive part of the genes, I am going to continue playing then.

Thank you very much for your fast response and good luck with your project!
